### ISSUE TITLE
Issue with shuffleLayerConfigurations when startIndex = 0

### ISSUE THREAD

**Issue by jalagar** [nftchef/art-engine#135] opened 2022-04-05 02:14 UTC
The problem is when shuffleLayerConfigurations is set to true, the length of abstractedIndexes is actually off by one, so the numbering is off.

For example, set growth edition to 10 and set shuffleLayerConfigurations to true, and set startIndex to 0, the resulting JSON has a chance that it will not start at 0 and include 1,2,3,4,5 or it will start at 0 and skip a number ex. 0,1,2,4,5. This is an easy fix, just set the loop to:
```
  for (
    let i = startIndex;
    i <=
    startIndex +
      layerConfigurations[layerConfigurations.length - 1].growEditionSizeTo - 1;
    i++
```
and subtract 1 if startIndex = 0. This may have to be changed for startIndex = 1 (or some other number) but still a bug

**Comment by nftchef** [comment] 2022-11-11 05:45
fixed. duplicate of #64 #66

**Closed by nftchef** 2022-11-11 05:45 UTC
